# Generated by Django 4.2.4 on 2023-08-30 16:43

from django.db import migrations, models
import staffs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[staffs.validators.validate_ethiopian_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('po_box', models.IntegerField(blank=True, null=True, verbose_name='P.O. Box')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('region_am', models.CharField(blank=True, max_length=150, null=True, validators=[staffs.validators.validate_amharic], verbose_name='ክልል')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('city_am', models.CharField(blank=True, max_length=150, null=True, validators=[staffs.validators.validate_amharic], verbose_name='ከተማ')),
                ('wereda', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda_am', models.CharField(blank=True, max_length=100, null=True, verbose_name='ወረዳ')),
                ('kebele', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
