# Generated by Django 4.2.4 on 2023-08-30 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import staffs.validators
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campuses', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('full_name_am', models.CharField(max_length=255, validators=[staffs.validators.validate_amharic], verbose_name='ሙሉ ስም')),
                ('relationship', models.CharField(max_length=255, verbose_name='relationship')),
                ('relationship_am', models.CharField(max_length=255, validators=[staffs.validators.validate_amharic], verbose_name='ዝምድና')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='emergency_adress', to='addresses.address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('first_name_am', models.CharField(max_length=100, validators=[staffs.validators.validate_amharic], verbose_name='ስም')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('last_name_am', models.CharField(max_length=100, validators=[staffs.validators.validate_amharic], verbose_name='የአባት ስም')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, default=students.models.get_default_photo, upload_to=students.models.get_student_photo_filepath)),
                ('qr_code', models.ImageField(editable=False, upload_to=students.models.get_student_qr_code_filepath)),
                ('date_of_birth', models.DateField(validators=[staffs.validators.validate_birth_date])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('government_id_number', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('financial_aid', models.BooleanField()),
                ('is_cafe_user', models.BooleanField(default=True)),
                ('is_student_associative', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='student_address', to='addresses.address')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='campuses.department')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.emergencycontact')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('PHONE', 'Phone'), ('PC', 'PC')], max_length=10)),
                ('device_model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=17)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='students.student')),
            ],
        ),
    ]
