# Generated by Django 4.2.4 on 2023-09-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinaryrecord',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='disciplinaryrecord',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disciplinaryrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_record', to='students.student'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_adress', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_address', to='addresses.address'),
        ),
    ]
