# Generated by Django 4.2.4 on 2023-08-30 16:43

from django.db import migrations, models
import django.db.models.deletion
import staffs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Campus Name')),
                ('name_am', models.CharField(max_length=255, validators=[staffs.validators.validate_amharic], verbose_name='የካምፓስ ስም')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='campus_address', to='addresses.address')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('name_am', models.CharField(max_length=255, validators=[staffs.validators.validate_amharic], verbose_name='የትምህርት ክፍል')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='campuses.campus')),
            ],
        ),
    ]
