# Generated by Django 4.2.4 on 2023-09-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_disciplinaryrecord_options_and_more'),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterField(
            model_name='library',
            name='student',
            field=models.OneToOneField(error_messages={'unique': 'The student did not return a book. ከዚቀደም የተዋሰውን መጽሐፍ አልመለሰም።'}, on_delete=django.db.models.deletion.PROTECT, related_name='rent_book', to='students.student'),
        ),
    ]
