# Generated by Django 4.2.4 on 2023-09-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
    ]
