# Generated by Django 4.2.4 on 2023-09-07 12:43

from django.db import migrations, models
import django.db.models.deletion
import staffs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_disciplinaryrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_period', models.CharField(max_length=20)),
                ('meal_period_am', models.CharField(max_length=20, validators=[staffs.validators.validate_amharic], verbose_name='የምግብ ሰዓት')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateField(auto_now_add=True)),
                ('time_checked', models.TimeField(auto_now_add=True)),
                ('meal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.mealperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'date_checked', 'meal_period')},
            },
        ),
    ]
