# Generated by Django 4.2.4 on 2023-09-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_attendance_time_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='ate_food',
            new_name='has_eaten',
        ),
    ]
