# Generated by Django 4.2.4 on 2023-09-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_rename_ate_food_attendance_has_eaten'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
